### ISSUE TITLE
this is not for the request~.

### ISSUE THREAD

**Issue by wangsgithub** [Baebeca-Solutions/dhcp-storm#1]
the bin is dhcptest with D lang, so it just send the package with discover, not the request~.

whatever u send any dis package, u can not occupy any ip from the dhcp server.

**Comment by Elompenta** [comment]
@wangsgithub 
The bin will not ACK the IP, this is correct.
Feel free to create a pull request and improve this Project.
The dhcptest exe, was forked from https://github.com/CyberShadow/dhcptest
